/** Responsive WebP assets — generated by `npm run encode-images`. */

export const HOMEPAGE_IMAGE_WIDTHS = [828, 1400, 2048]

/** Native pixel widths of encoded sources (must match PNG dimensions in public/). */
export const IMAGE_NATIVE_WIDTHS = {
  '/building-full.webp': 4572,
  '/building-95-blurred.webp': 1920,
  '/homepage-background.webp': 2400,
  '/homepage-background-dark.webp': 2400,
  '/homepage-background-blur.webp': 2400,
  '/homepage-background-blur-dark.webp': 2400,
}

/** Campus backdrop — overscan + parallax zoom headroom. */
export const HOMEPAGE_RESPONSIVE_SIZES =
  '(max-width: 828px) 150vw, (max-width: 1400px) 1400px, 2048px'

/** Building cutaway — accounts for mobile camera scale up to ~1.9x. */
export const BUILDING_RESPONSIVE_SIZES =
  '(max-width: 828px) 200vw, (max-width: 1400px) 120vw, 2048px'

/** Hero blur only — smaller asset; cap hint so browser does not request missing -2048 variant. */
export const BUILDING_BLUR_RESPONSIVE_SIZES =
  '(max-width: 828px) 100vw, (max-width: 1400px) 70vw, 1920px'

/**
 * Build srcSet from generated width variants.
 * When native width is below 2048, omit -2048.webp and use the full .webp as largest candidate.
 */
function buildSrcSet(basePath) {
  const stem = basePath.replace(/\.webp$/, '')
  const nativeWidth = IMAGE_NATIVE_WIDTHS[basePath] ?? null
  const variantWidths = nativeWidth
    ? HOMEPAGE_IMAGE_WIDTHS.filter((width) => width < nativeWidth)
    : HOMEPAGE_IMAGE_WIDTHS

  const parts = variantWidths.map((width) => `${stem}-${width}.webp ${width}w`)

  if (nativeWidth && nativeWidth < Math.max(...HOMEPAGE_IMAGE_WIDTHS)) {
    parts.push(`${basePath} ${nativeWidth}w`)
  }

  return parts.join(', ')
}

export const HOMEPAGE_BACKGROUNDS = {
  light: '/homepage-background.webp',
  dark: '/homepage-background-dark.webp',
}

export const HOMEPAGE_BLUR_BACKGROUNDS = {
  light: '/homepage-background-blur.webp',
  dark: '/homepage-background-blur-dark.webp',
}

export const HOMEPAGE_BACKGROUND_SRCSETS = {
  light: buildSrcSet(HOMEPAGE_BACKGROUNDS.light),
  dark: buildSrcSet(HOMEPAGE_BACKGROUNDS.dark),
}

export const HOMEPAGE_BLUR_BACKGROUND_SRCSETS = {
  light: buildSrcSet(HOMEPAGE_BLUR_BACKGROUNDS.light),
  dark: buildSrcSet(HOMEPAGE_BLUR_BACKGROUNDS.dark),
}

export const BUILDING_SHARP_SRC = '/building-full.webp'
export const BUILDING_SHARP_SRCSET = buildSrcSet(BUILDING_SHARP_SRC)

export const BUILDING_BLUR_SRC = '/building-95-blurred.webp'
export const BUILDING_BLUR_SRCSET = buildSrcSet(BUILDING_BLUR_SRC)

/** Preload targets (1400w — sharper hero on phone, still reasonable bytes). */
export const BUILDING_SHARP_PRELOAD = '/building-full-1400.webp'
export const BUILDING_BLUR_PRELOAD = '/building-95-blurred-1400.webp'
