export const PRICING_TIERS = [
  {
    name: 'Starter',
    price: '$49',
    period: '/month',
    description: 'Perfect for small operations getting organized.',
    features: [
      'Up to 5 team members',
      '1 factory location',
      'Basic order management',
      'Inventory tracking',
      'Email support',
    ],
    cta: 'Start free trial',
    highlighted: false,
  },
  {
    name: 'Pro',
    price: '$149',
    period: '/month',
    description: 'For growing businesses with multiple locations.',
    features: [
      'Up to 25 team members',
      'Unlimited factories',
      'Advanced workflows',
      'Machine tracking',
      'Production planning',
      'Custom reports',
      'Priority support',
    ],
    cta: 'Start free trial',
    highlighted: true,
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    period: '',
    description: 'For large-scale operations with complex needs.',
    features: [
      'Unlimited team members',
      'Unlimited everything',
      'Custom integrations',
      'Dedicated account manager',
      'SLA guarantee',
      'On-premise deployment',
      '24/7 phone support',
    ],
    cta: 'Contact sales',
    highlighted: false,
  },
]
